#!/bin/bash
set -e

case "$1" in
    remove|deconfigure)
        if command -v systemctl >/dev/null 2>&1; then
            systemctl stop documentdb-postgresql || true
            systemctl disable documentdb-postgresql || true
            systemctl stop documentdb-gateway || true
            systemctl disable documentdb-gateway || true
        fi
        ;;
    upgrade)
        if command -v systemctl >/dev/null 2>&1; then
            systemctl stop documentdb-postgresql || true
            systemctl stop documentdb-gateway || true
        fi
        ;;
esac

exit 0
