site_name: DocumentDB
theme:
  name: material

nav:
  - Home: index.md
  - Design Doc: doc_design.md
  - Version 1.0:
      - Getting Started: v1/documentdb.md
      - Prebuild Image: v1/prebuild.md
      - Packaging: v1/packaging.md
  - Version 2.0:
      - Getting Started: v2/documentdb.md
      - Prebuild Image: v2/prebuild.md
      - Packaging: v2/packaging.md

plugins:
  - search

markdown_extensions:
  - admonition
  - toc:
      permalink: true
