site_name: DocumentDB
repo_url: https://github.com/microsoft/documentdb
theme:
  name: readthedocs

nav:
  - DocumentDB:
      - Version 0.103: v1/index.md

plugins:
  - search

markdown_extensions:
  - admonition
  - toc:
      permalink: true
