site_name: DocumentDB
repo_url: https://github.com/microsoft/documentdb
theme:
  name: readthedocs

nav:
  - Version 1.0:
      - Document DB: v1/index.md

plugins:
  - search

markdown_extensions:
  - admonition
  - toc:
      permalink: true
