import json
import os
import re
import subprocess
import tempfile
import textwrap
import time
import unittest
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
ENTRYPOINT = REPO_ROOT / "documentdb-local" / "scripts" / "emulator_entrypoint.sh"
GATEWAY_RBAC_UTILS = (
    REPO_ROOT
    / "pg_documentdb_gw"
    / "documentdb_tests"
    / "src"
    / "utils"
    / "rbac_utils.rs"
)


class EmulatorEntrypointTests(unittest.TestCase):
    def setUp(self):
        self.temp_dir = tempfile.TemporaryDirectory()
        self.root = Path(self.temp_dir.name)
        self.gateway_home = self.root / "gateway"
        self.gateway_scripts = self.gateway_home / "scripts"
        self.gateway_config_dir = self.gateway_home / "pg_documentdb_gw"
        self.gateway_target_dir = self.gateway_config_dir / "target"
        self.sample_data_dir = self.gateway_home / "sample-data"
        self.bin_dir = self.root / "bin"
        self.logs_dir = self.root / "logs"
        self.data_dir = self.root / "data"

        self.gateway_scripts.mkdir(parents=True)
        self.gateway_target_dir.mkdir(parents=True)
        self.sample_data_dir.mkdir(parents=True)
        self.bin_dir.mkdir(parents=True)
        self.logs_dir.mkdir(parents=True)
        self.data_dir.mkdir(parents=True)

        (self.gateway_config_dir / "SetupConfiguration.json").write_text(
            json.dumps(
                {
                    "NodeHostName": "localhost",
                    "BlockedRolePrefixes": ["documentdb"],
                    "PostgresPort": 9712,
                    "GatewayListenPort": 10260,
                    "HostConfigurationWatchIntervalMs": 1000,
                    "CertificateOptions": {"CertType": "PemAutoGenerated"},
                    "UseLocalHost": False,
                }
            ),
            encoding="utf-8",
        )

        self._write_exec(
            self.bin_dir / "sudo",
            """#!/bin/sh
if [ "$1" = "chown" ]; then
  exit 0
fi
exec "$@"
""",
        )
        self._write_exec(self.bin_dir / "nc", "#!/bin/sh\nexit 0\n")
        self._write_exec(self.bin_dir / "tail", "#!/bin/sh\nexit 0\n")
        self._write_exec(
            self.bin_dir / "jq",
            """#!/usr/bin/env python3
import json
import sys
args = sys.argv[1:]
raw = False
vars = {}
while args and args[0].startswith('-'):
    if args[0] in ('--arg', '--argjson'):
        flag, name, value, *args = args
        vars[name] = json.loads(value) if flag == '--argjson' else value
    elif args[0] in ('-r', '--raw-output'):
        raw = True
        args = args[1:]
    else:
        args = args[1:]
expr, file_path = args
with open(file_path, 'r', encoding='utf-8') as f:
    data = json.load(f)
expr = expr.strip()
if expr == '.BlockedRolePrefixes | type':
    v = data.get('BlockedRolePrefixes')
    if v is None:
        print('null')
    elif isinstance(v, bool):
        print('boolean')
    elif isinstance(v, list):
        print('array')
    elif isinstance(v, str):
        print('string')
    elif isinstance(v, (int, float)):
        print('number')
    else:
        print('object')
    raise SystemExit(0)
if expr == 'all(.BlockedRolePrefixes[]; type == "string")':
    arr = data.get('BlockedRolePrefixes') or []
    ok = isinstance(arr, list) and all(isinstance(x, str) for x in arr)
    raise SystemExit(0 if ok else 1)
if expr in ('.BlockedRolePrefixes[]', '.BlockedRolePrefixes[]?'):
    for item in data.get('BlockedRolePrefixes', []):
        print(item)
    raise SystemExit(0)
if expr.startswith('.GatewayListenPort = '):
    data['GatewayListenPort'] = int(expr.split('=', 1)[1].strip())
elif expr.startswith('.PostgresPort = '):
    data['PostgresPort'] = int(expr.split('=', 1)[1].strip())
elif expr.startswith('.TlsMode = '):
    data['TlsMode'] = vars.get('tlsMode', expr.split('=', 1)[1].strip().strip('"'))
elif expr.startswith('.EnforceTls = '):
    data['EnforceTls'] = vars['enforceTls']
elif expr.startswith('.CertificateOptions = '):
    data['CertificateOptions'] = {
        'CertType': 'PemFile',
        'FilePath': vars['certPath'],
        'KeyFilePath': vars['keyFilePath'],
    }
else:
    raise SystemExit(f'Unsupported jq expression: {expr}')
json.dump(data, sys.stdout)
""",
        )

        self._write_exec(
            self.gateway_scripts / "build_and_start_gateway.sh",
            "#!/bin/sh\necho gateway-stub-started\n",
        )
        self._write_exec(
            self.gateway_scripts / "start_oss_server.sh",
            "#!/bin/sh\necho oss-server-stub-started\n",
        )
        self._write_exec(
            self.gateway_scripts / "init_documentdb_data.sh",
            "#!/bin/sh\necho init-script-stub-started\n",
        )

    def tearDown(self):
        self.temp_dir.cleanup()

    def _write_exec(self, path: Path, content: str):
        path.write_text(textwrap.dedent(content), encoding="utf-8")
        path.chmod(0o755)

    def _run_entrypoint(self, *args, extra_env=None):
        env = os.environ.copy()
        env.update(
            {
                "PATH": f"{self.bin_dir}:{env['PATH']}",
                "GATEWAY_HOME": str(self.gateway_home),
                "DOCUMENTDB_LOG_DIR": str(self.logs_dir),
                "SYSTEM_POSTGRES_LOG": str(self.root / "postgres-system.log"),
                "START_POSTGRESQL": "false",
                "SKIP_INIT_DATA": "true",
                "CREATE_USER": "false",
                "PASSWORD": "mypassword",
                "DATA_PATH": str(self.data_dir),
                "USERNAME": "default_user",
                "OWNER": "documentdb",
            }
        )
        if extra_env:
            env.update(extra_env)
        return subprocess.run(
            ["bash", str(ENTRYPOINT), *args],
            cwd=REPO_ROOT,
            env=env,
            text=True,
            capture_output=True,
            timeout=30,
        )

    def _read_config(self):
        with (self.gateway_target_dir / "SetupConfiguration_temp.json").open(
            "r", encoding="utf-8"
        ) as file:
            return json.load(file)

    def _configure_postgres_stubs(self, psql_exit_code=0):
        sql_capture = self.root / "psql-input.sql"
        self._write_exec(
            self.gateway_scripts / "start_oss_server.sh",
            f"""#!/bin/sh
touch "{self.data_dir / 'postmaster.pid'}" "{self.data_dir / 'pglog.log'}"
echo oss-server-stub-started
""",
        )
        self._write_exec(
            self.bin_dir / "psql",
            f"""#!/bin/sh
cat > "{sql_capture}"
exit {psql_exit_code}
""",
        )
        return sql_capture

    def test_get_parameter_stub_returns_command_not_supported(self):
        sql_capture = self._configure_postgres_stubs()

        result = self._run_entrypoint(extra_env={"START_POSTGRESQL": "true"})

        self.assertEqual(result.returncode, 0, msg=result.stdout + result.stderr)
        sql = sql_capture.read_text(encoding="utf-8")
        self.assertIn(
            "to_regprocedure('documentdb_api.get_parameter(boolean,boolean,text[])') IS NULL",
            sql,
        )
        self.assertIn(
            "CREATE FUNCTION documentdb_api.get_parameter(boolean, boolean, text[])",
            sql,
        )
        self.assertIn('"code": 115', sql)
        self.assertIn('"codeName": "CommandNotSupported"', sql)
        self.assertIn('"ok": 0.0', sql)
        self.assertIn(
            "documentdb-local temporary CommandNotSupported stub for issue #650",
            sql,
        )
        self.assertNotIn("CREATE OR REPLACE FUNCTION", sql)
        self.assertNotIn("featureCompatibilityVersion", sql)
        self.assertNotIn("'7.0'", sql)
        self.assertIn(
            "Ensuring unsupported getParameter returns CommandNotSupported",
            result.stdout,
        )

    def test_get_parameter_stub_install_failure_aborts_startup(self):
        self._configure_postgres_stubs(psql_exit_code=1)

        result = self._run_entrypoint(extra_env={"START_POSTGRESQL": "true"})

        self.assertNotEqual(result.returncode, 0)
        self.assertIn(
            "could not install the documentdb-local getParameter rejection stub",
            result.stdout + result.stderr,
        )
        self.assertNotIn("Starting gateway in the background", result.stdout)

    def test_get_parameter_stub_is_not_installed_in_external_postgres(self):
        psql_called = self.root / "psql-called"
        self._write_exec(
            self.bin_dir / "psql",
            f"""#!/bin/sh
touch "{psql_called}"
exit 1
""",
        )

        result = self._run_entrypoint(extra_env={"START_POSTGRESQL": "false"})

        self.assertEqual(result.returncode, 0, msg=result.stdout + result.stderr)
        self.assertFalse(psql_called.exists())
        self.assertIn("Skipping PostgreSQL server start", result.stdout)

    def test_default_mode_sets_allowTLS_in_config(self):
        result = self._run_entrypoint("--password", "mypassword")
        self.assertEqual(result.returncode, 0, msg=result.stdout + result.stderr)
        config = self._read_config()
        self.assertEqual(config["TlsMode"], "allowTLS")
        self.assertEqual(config["EnforceTls"], False)
        self.assertEqual(config["GatewayListenPort"], 10260)
        self.assertEqual(config["PostgresPort"], 9712)
        self.assertNotIn("does not turn TLS off", result.stdout + result.stderr)

    def test_tlsMode_requireTLS_flag_sets_requireTLS_in_config(self):
        result = self._run_entrypoint(
            "--password", "mypassword", "--tlsMode", "requireTLS"
        )
        self.assertEqual(result.returncode, 0, msg=result.stdout + result.stderr)
        config = self._read_config()
        self.assertEqual(config["TlsMode"], "requireTLS")
        self.assertEqual(config["EnforceTls"], True)

    def test_tlsMode_disabled_flag_sets_disabled_in_config(self):
        result = self._run_entrypoint(
            "--password", "mypassword", "--tlsMode", "disabled"
        )
        self.assertEqual(result.returncode, 0, msg=result.stdout + result.stderr)
        config = self._read_config()
        self.assertEqual(config["TlsMode"], "disabled")
        self.assertEqual(config["EnforceTls"], False)
        self.assertIn("does not turn TLS off", result.stdout + result.stderr)

    def test_tlsMode_env_var_sets_mode_in_config(self):
        result = self._run_entrypoint(
            "--password",
            "mypassword",
            extra_env={"TLS_MODE": "requireTLS"},
        )
        self.assertEqual(result.returncode, 0, msg=result.stdout + result.stderr)
        config = self._read_config()
        self.assertEqual(config["TlsMode"], "requireTLS")
        self.assertEqual(config["EnforceTls"], True)

    def test_tlsMode_env_var_allowTLS_does_not_enforce_tls(self):
        result = self._run_entrypoint(
            "--password",
            "mypassword",
            extra_env={"TLS_MODE": "allowTLS"},
        )
        self.assertEqual(result.returncode, 0, msg=result.stdout + result.stderr)
        config = self._read_config()
        self.assertEqual(config["TlsMode"], "allowTLS")
        self.assertEqual(config["EnforceTls"], False)

    def test_system_postgres_log_defaults_to_runtime_pg_version(self):
        result = self._run_entrypoint(
            "--password",
            "mypassword",
            extra_env={"PG_VERSION_USED": "18", "SYSTEM_POSTGRES_LOG": ""},
        )
        self.assertEqual(result.returncode, 0, msg=result.stdout + result.stderr)
        self.assertIn(
            "System PostgreSQL logs (/var/log/postgresql/postgresql-18-main.log)",
            result.stdout,
        )

    def test_invalid_tlsMode_value_fails_fast(self):
        result = self._run_entrypoint(
            "--password",
            "mypassword",
            extra_env={"TLS_MODE": "maybe"},
        )
        self.assertNotEqual(result.returncode, 0)
        self.assertIn(
            "Invalid tlsMode value 'maybe', must be one of: disabled, allowTLS, requireTLS",
            result.stdout + result.stderr,
        )

    def test_enforce_tls_write_failure_aborts(self):
        failing_jq = """#!/usr/bin/env python3
import json
import sys
args = sys.argv[1:]
raw = False
vars = {}
while args and args[0].startswith('-'):
    if args[0] in ('--arg', '--argjson'):
        flag, name, value, *args = args
        vars[name] = json.loads(value) if flag == '--argjson' else value
    elif args[0] in ('-r', '--raw-output'):
        raw = True
        args = args[1:]
    else:
        args = args[1:]
expr, file_path = args
expr = expr.strip()
if expr == '.BlockedRolePrefixes | type':
    with open(file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    v = data.get('BlockedRolePrefixes')
    if v is None:
        print('null')
    elif isinstance(v, bool):
        print('boolean')
    elif isinstance(v, list):
        print('array')
    elif isinstance(v, str):
        print('string')
    elif isinstance(v, (int, float)):
        print('number')
    else:
        print('object')
    raise SystemExit(0)
if expr == 'all(.BlockedRolePrefixes[]; type == "string")':
    with open(file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    arr = data.get('BlockedRolePrefixes') or []
    ok = isinstance(arr, list) and all(isinstance(x, str) for x in arr)
    raise SystemExit(0 if ok else 1)
if expr in ('.BlockedRolePrefixes[]', '.BlockedRolePrefixes[]?'):
    with open(file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    for item in data.get('BlockedRolePrefixes', []):
        print(item)
    raise SystemExit(0)
if expr.startswith('.EnforceTls = '):
    sys.stderr.write('jq: simulated failure\\n')
    sys.exit(1)
with open(file_path, 'r', encoding='utf-8') as f:
    data = json.load(f)
if expr.startswith('.GatewayListenPort = '):
    data['GatewayListenPort'] = int(expr.split('=', 1)[1].strip())
elif expr.startswith('.PostgresPort = '):
    data['PostgresPort'] = int(expr.split('=', 1)[1].strip())
elif expr.startswith('.TlsMode = '):
    data['TlsMode'] = vars.get('tlsMode', expr.split('=', 1)[1].strip().strip('"'))
else:
    raise SystemExit(f'Unsupported jq expression: {expr}')
json.dump(data, sys.stdout)
"""
        self._write_exec(self.bin_dir / "jq", failing_jq)
        result = self._run_entrypoint("--password", "mypassword")
        self.assertNotEqual(result.returncode, 0)
        self.assertIn(
            "failed to write EnforceTls to the gateway configuration file",
            result.stdout + result.stderr,
        )

    def test_pem_certificate_and_key_are_written_to_config(self):
        result = self._run_entrypoint(
            "--password",
            "mypassword",
            "--cert-path",
            "/tmp/documentdb-local.pem",
            "--key-file",
            "/tmp/documentdb-local.key",
        )
        self.assertEqual(result.returncode, 0, msg=result.stdout + result.stderr)
        config = self._read_config()
        self.assertEqual(
            config["CertificateOptions"],
            {
                "CertType": "PemFile",
                "FilePath": "/tmp/documentdb-local.pem",
                "KeyFilePath": "/tmp/documentdb-local.key",
            },
        )

    def test_pfx_certificate_without_key_file_is_rejected(self):
        result = self._run_entrypoint(
            "--password",
            "mypassword",
            "--cert-path",
            "/tmp/documentdb-local.pfx",
        )
        self.assertNotEqual(result.returncode, 0)
        self.assertIn(
            "Error: Both CERT_PATH and KEY_FILE must be set together, or neither should be set.",
            result.stdout + result.stderr,
        )

    def test_key_file_without_certificate_is_rejected(self):
        result = self._run_entrypoint(
            "--password",
            "mypassword",
            "--key-file",
            "/tmp/documentdb-local.key",
        )
        self.assertNotEqual(result.returncode, 0)
        self.assertIn(
            "Error: Both CERT_PATH and KEY_FILE must be set together, or neither should be set.",
            result.stdout + result.stderr,
        )

    def test_help_describes_tlsMode_and_pem_certificate_requirements(self):
        result = self._run_entrypoint("--help")
        self.assertEqual(result.returncode, 0, msg=result.stdout + result.stderr)
        self.assertIn("--tlsMode", result.stdout)
        self.assertIn(
            "By default, the gateway accepts both plain and TLS connections",
            result.stdout,
        )
        self.assertIn("Specify a path to a PEM certificate", result.stdout)
        self.assertIn(
            "PEM certificates must be provided together with --key-file.",
            result.stdout,
        )
        self.assertNotIn("CERT_SECRET", result.stdout)

    def _write_counting_init_stub(self, fail_on_second=False, fail_always=False):
        """Replace the init-data stub with one that records each invocation.

        The counter persists under the data dir so it survives across the two
        entrypoint runs in a single test, simulating a container restart on a
        persistent volume. The stub also emulates the real script's
        --attempt-marker contract: it creates the marker before doing any work,
        so the entrypoint's one-shot skip behaves as in production (#612).
        """
        counter = self.data_dir / "init_invocations"
        # The two failure modes generate conflicting stub logic, so disallow combining them.
        assert not (
            fail_on_second and fail_always
        ), "fail_on_second and fail_always are mutually exclusive"
        fail_block = ""
        if fail_on_second:
            fail_block = (
                'if [ "$count" -ge 2 ]; then\n'
                '  echo "init-stub: refusing repeat invocation"\n'
                "  exit 1\n"
                "fi\n"
            )
        if fail_always:
            fail_block += 'echo "init-stub: simulated failure"\nexit 1\n'
        self._write_exec(
            self.gateway_scripts / "init_documentdb_data.sh",
            f"#!/bin/sh\n"
            f'attempt_marker=""\n'
            f"while [ $# -gt 0 ]; do\n"
            f'  case "$1" in\n'
            f'    --attempt-marker) attempt_marker="$2"; shift 2 ;;\n'
            f"    *) shift ;;\n"
            f"  esac\n"
            f"done\n"
            f'if [ -n "$attempt_marker" ]; then\n'
            f'  mkdir -p "$(dirname "$attempt_marker")" && touch "$attempt_marker"\n'
            f"fi\n"
            f"count=0\n"
            f'if [ -f "{counter}" ]; then count=$(cat "{counter}"); fi\n'
            f"count=$((count + 1))\n"
            f'echo "$count" > "{counter}"\n'
            f'echo "init-stub invocation $count"\n'
            f"{fail_block}"
            f"exit 0\n",
        )
        return counter

    def test_sample_data_is_seeded_once_and_skipped_on_restart(self):
        # Make the sample-data dir resemble the real layout.
        (self.sample_data_dir / "01-sample.js").write_text(
            "// sample\n", encoding="utf-8"
        )
        # The stub fails if invoked a second time, so this test fails unless the
        # marker prevents a re-seed on the simulated restart (#612).
        counter = self._write_counting_init_stub(fail_on_second=True)
        env = {"INIT_DATA": "true", "SKIP_INIT_DATA": ""}

        first = self._run_entrypoint(extra_env=env)
        self.assertEqual(first.returncode, 0, msg=first.stdout + first.stderr)
        self.assertEqual(counter.read_text().strip(), "1")
        marker = self.data_dir / ".documentdb-local" / "sample_data_initialized"
        self.assertTrue(marker.exists(), "marker should be written after first seed")

        # Second boot against the same persistent data dir must skip the seed.
        second = self._run_entrypoint(extra_env=env)
        self.assertEqual(second.returncode, 0, msg=second.stdout + second.stderr)
        self.assertEqual(
            counter.read_text().strip(), "1", "seed must not run again on restart"
        )
        self.assertIn("already initialized", second.stdout)
        self.assertIn("fresh data volume", second.stdout)

    def test_custom_data_is_one_shot_on_restart(self):
        init_dir = self.root / "custom_init"
        init_dir.mkdir()
        (init_dir / "00-custom.js").write_text("// custom\n", encoding="utf-8")
        # Fails if invoked a second time, so this test fails unless the marker
        # prevents the custom init from re-running on a simulated restart (#612).
        counter = self._write_counting_init_stub(fail_on_second=True)
        env = {
            "INIT_DATA": "false",
            "SKIP_INIT_DATA": "",
            "INIT_DATA_PATH": str(init_dir),
        }

        first = self._run_entrypoint(extra_env=env)
        self.assertEqual(first.returncode, 0, msg=first.stdout + first.stderr)
        self.assertEqual(counter.read_text().strip(), "1")
        attempt_marker = self.data_dir / ".documentdb-local" / "custom_data_attempted"
        success_marker = self.data_dir / ".documentdb-local" / "custom_data_succeeded"
        self.assertTrue(attempt_marker.exists(), "attempt marker should be written")
        self.assertTrue(
            success_marker.exists(), "success marker should be written after a successful run"
        )

        second = self._run_entrypoint(extra_env=env)
        self.assertEqual(second.returncode, 0, msg=second.stdout + second.stderr)
        self.assertEqual(
            counter.read_text().strip(), "1", "custom init must not run again on restart"
        )
        self.assertIn("already initialized", second.stdout)

    def test_custom_data_failure_is_not_retried_on_restart(self):
        # A failing custom init (e.g. a non-idempotent user script that errors partway)
        # must not loop: the attempt marker is written before the script runs, so the
        # failed init is not re-run on restart (#612). Matches the official-image contract.
        init_dir = self.root / "custom_init"
        init_dir.mkdir()
        (init_dir / "00-custom.js").write_text("// custom\n", encoding="utf-8")
        counter = self._write_counting_init_stub(fail_always=True)
        env = {
            "INIT_DATA": "false",
            "SKIP_INIT_DATA": "",
            "INIT_DATA_PATH": str(init_dir),
        }

        first = self._run_entrypoint(extra_env=env)
        self.assertNotEqual(
            first.returncode, 0, msg="first boot should surface the init failure"
        )
        self.assertEqual(counter.read_text().strip(), "1")
        attempt_marker = self.data_dir / ".documentdb-local" / "custom_data_attempted"
        success_marker = self.data_dir / ".documentdb-local" / "custom_data_succeeded"
        self.assertTrue(
            attempt_marker.exists(),
            "attempt marker must be written before running so a failed init is not retried",
        )
        self.assertFalse(
            success_marker.exists(), "success marker must not exist after a failed init"
        )

        second = self._run_entrypoint(extra_env=env)
        self.assertEqual(second.returncode, 0, msg=second.stdout + second.stderr)
        self.assertEqual(
            counter.read_text().strip(),
            "1",
            "failed custom init must not be retried on restart",
        )
        self.assertIn("attempted but its success was not recorded", second.stdout)
        self.assertIn("fresh data volume", second.stdout)
        self.assertNotIn("already initialized", second.stdout)

    def test_custom_failure_then_sample_runs_on_next_boot(self):
        # Custom init runs before sample. If custom fails on the first boot the container
        # exits; on restart custom is skipped (one-shot) and sample then seeds (#612).
        init_dir = self.root / "custom_init"
        init_dir.mkdir()
        (init_dir / "00-custom.js").write_text("// custom\n", encoding="utf-8")
        (self.sample_data_dir / "01-sample.js").write_text("// sample\n", encoding="utf-8")
        # Stub fails (after marking) when invoked for custom (--attempt-marker present)
        # and succeeds for sample (no --attempt-marker).
        self._write_exec(
            self.gateway_scripts / "init_documentdb_data.sh",
            "#!/bin/sh\n"
            'attempt_marker=""\n'
            "while [ $# -gt 0 ]; do\n"
            '  case "$1" in\n'
            '    --attempt-marker) attempt_marker="$2"; shift 2 ;;\n'
            "    *) shift ;;\n"
            "  esac\n"
            "done\n"
            'if [ -n "$attempt_marker" ]; then\n'
            '  mkdir -p "$(dirname "$attempt_marker")" && touch "$attempt_marker"\n'
            '  echo "custom init failing"\n'
            "  exit 1\n"
            "fi\n"
            'echo "sample init ok"\n'
            "exit 0\n",
        )
        env = {
            "INIT_DATA": "true",
            "SKIP_INIT_DATA": "",
            "INIT_DATA_PATH": str(init_dir),
        }

        first = self._run_entrypoint(extra_env=env)
        self.assertNotEqual(
            first.returncode, 0, msg="custom failure should fail the first boot"
        )
        attempt_marker = self.data_dir / ".documentdb-local" / "custom_data_attempted"
        sample_marker = self.data_dir / ".documentdb-local" / "sample_data_initialized"
        self.assertTrue(attempt_marker.exists())
        self.assertFalse(
            sample_marker.exists(), "sample must not seed when custom fails first"
        )

        second = self._run_entrypoint(extra_env=env)
        self.assertEqual(second.returncode, 0, msg=second.stdout + second.stderr)
        self.assertTrue(
            sample_marker.exists(),
            "sample should seed on the next boot after custom is skipped",
        )
        self.assertIn("attempted but its success was not recorded", second.stdout)

    def test_help_does_not_advertise_force_init_data(self):
        # Re-initialization is intentionally done by starting with a fresh data
        # volume (common container-image parity), not a force flag (#612).
        result = self._run_entrypoint("--help")
        self.assertEqual(result.returncode, 0, msg=result.stdout + result.stderr)
        self.assertNotIn("--force-init-data", result.stdout)

    def test_sample_data_scripts_are_idempotent(self):
        sample_dir = REPO_ROOT / "documentdb-local" / "sample-data"
        scripts = sorted(sample_dir.glob("*.js"))
        self.assertTrue(scripts, "expected bundled sample-data scripts to exist")
        for js in scripts:
            text = js.read_text(encoding="utf-8")
            self.assertNotIn(
                ".insertMany(",
                text,
                msg=f"{js.name} uses insertMany, which is not idempotent on restart (#612)",
            )
            self.assertIn(
                "countDocuments(",
                text,
                msg=f"{js.name} should guard inserts with an existence check (#612)",
            )

    def _set_blocked_role_prefixes(self, prefixes):
        config_path = self.gateway_config_dir / "SetupConfiguration.json"
        config = json.loads(config_path.read_text(encoding="utf-8"))
        config["BlockedRolePrefixes"] = prefixes
        config_path.write_text(json.dumps(config), encoding="utf-8")

    def _gateway_reserved_role_names(self):
        source = GATEWAY_RBAC_UTILS.read_text(encoding="utf-8")
        match = re.search(
            r"pub const RESERVED_ROLE_NAMES:.*?= &\[(.*?)\];",
            source,
            re.DOTALL,
        )
        self.assertIsNotNone(
            match,
            "could not find the gateway RESERVED_ROLE_NAMES registry",
        )
        role_names = re.findall(r'"([^"]+)"', match.group(1))
        self.assertTrue(role_names, "gateway reserved-role registry is empty")
        return role_names

    def test_blocked_username_prefix_is_rejected(self):
        # citus is the username in the issue #650 reproduction; documentdb is the
        # prefix the default test config blocks. Either must fail fast at startup
        # rather than letting the container report ready with an unusable user.
        result = self._run_entrypoint(
            "--password", "mypassword", extra_env={"USERNAME": "documentdb_user"}
        )
        self.assertNotEqual(result.returncode, 0)
        self.assertIn(
            "username 'documentdb_user' uses reserved prefix 'documentdb'",
            result.stdout + result.stderr,
        )

    def test_blocked_username_prefix_is_case_insensitive(self):
        result = self._run_entrypoint(
            "--password", "mypassword", extra_env={"USERNAME": "DocumentDBAdmin"}
        )
        self.assertNotEqual(result.returncode, 0)
        self.assertIn(
            "uses reserved prefix 'documentdb'",
            result.stdout + result.stderr,
        )

    def test_allowed_username_passes_validation(self):
        result = self._run_entrypoint(
            "--password", "mypassword", extra_env={"USERNAME": "docdb_admin"}
        )
        self.assertEqual(result.returncode, 0, msg=result.stdout + result.stderr)
        self.assertNotIn("reserved prefix", result.stdout + result.stderr)

    def test_all_configured_blocked_prefixes_are_rejected(self):
        prefixes = ["documentdb", "citus", "pg", "internal_role"]
        self._set_blocked_role_prefixes(prefixes)
        for prefix in prefixes:
            username = f"{prefix}_service"
            with self.subTest(username=username):
                result = self._run_entrypoint(
                    "--password", "mypassword", extra_env={"USERNAME": username}
                )
                self.assertNotEqual(result.returncode, 0)
                self.assertIn(
                    f"uses reserved prefix '{prefix}'",
                    result.stdout + result.stderr,
                )

    def test_all_gateway_reserved_role_names_are_rejected(self):
        # Registered internal roles remain reserved even when the independent
        # BlockedRolePrefixes policy is empty.
        self._set_blocked_role_prefixes([])
        for username in self._gateway_reserved_role_names():
            with self.subTest(username=username):
                result = self._run_entrypoint(
                    "--password", "mypassword", extra_env={"USERNAME": username}
                )
                self.assertNotEqual(result.returncode, 0)
                self.assertIn(
                    "is reserved for an internal DocumentDB role",
                    result.stdout + result.stderr,
                )

    def test_empty_blocked_prefix_entry_fails_fast(self):
        # The gateway's starts_with("") matches every username, so an empty
        # BlockedRolePrefixes entry blocks all authentication. The entrypoint
        # must fail fast rather than start a container whose user can never
        # authenticate -- even for an otherwise-allowed username.
        self._set_blocked_role_prefixes([""])
        result = self._run_entrypoint(
            "--password", "mypassword", extra_env={"USERNAME": "docdb_admin"}
        )
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("contains an empty entry", result.stdout + result.stderr)

    def test_missing_gateway_config_fails_fast(self):
        # Validation reads the gateway's own SetupConfiguration.json; if it is
        # missing the check must not silently pass (which would re-open the
        # false-success-startup bug), it must fail fast.
        (self.gateway_config_dir / "SetupConfiguration.json").unlink()
        result = self._run_entrypoint(
            "--password", "mypassword", extra_env={"USERNAME": "docdb_admin"}
        )
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("not found", result.stdout + result.stderr)

    def test_unparseable_gateway_config_fails_fast(self):
        config_path = self.gateway_config_dir / "SetupConfiguration.json"
        config_path.write_text("{not valid json", encoding="utf-8")
        result = self._run_entrypoint(
            "--password", "mypassword", extra_env={"USERNAME": "docdb_admin"}
        )
        self.assertNotEqual(result.returncode, 0)
        self.assertIn(
            "failed to parse gateway configuration",
            result.stdout + result.stderr,
        )

    def test_non_array_blocked_role_prefixes_fails_fast(self):
        # A syntactically valid config whose BlockedRolePrefixes is not an array
        # (the gateway requires an array of strings) must fail fast rather than
        # be silently treated as "no prefixes", which would re-open the
        # false-success-startup bug.
        config_path = self.gateway_config_dir / "SetupConfiguration.json"
        config = json.loads(config_path.read_text(encoding="utf-8"))
        config["BlockedRolePrefixes"] = "documentdb"
        config_path.write_text(json.dumps(config), encoding="utf-8")
        result = self._run_entrypoint(
            "--password", "mypassword", extra_env={"USERNAME": "docdb_admin"}
        )
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("must be a JSON array", result.stdout + result.stderr)

    def _write_raw_config(self, mutate):
        config_path = self.gateway_config_dir / "SetupConfiguration.json"
        config = json.loads(config_path.read_text(encoding="utf-8"))
        mutate(config)
        config_path.write_text(json.dumps(config), encoding="utf-8")

    def test_missing_blocked_role_prefixes_key_fails_fast(self):
        # The gateway requires BlockedRolePrefixes (non-defaulted Vec<String>), so
        # an absent key is invalid; validate the same contract instead of silently
        # skipping and letting the gateway fail later.
        self._write_raw_config(lambda c: c.pop("BlockedRolePrefixes", None))
        result = self._run_entrypoint(
            "--password", "mypassword", extra_env={"USERNAME": "docdb_admin"}
        )
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("must be a JSON array", result.stdout + result.stderr)

    def test_null_blocked_role_prefixes_fails_fast(self):
        self._write_raw_config(
            lambda c: c.__setitem__("BlockedRolePrefixes", None)
        )
        result = self._run_entrypoint(
            "--password", "mypassword", extra_env={"USERNAME": "docdb_admin"}
        )
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("must be a JSON array", result.stdout + result.stderr)

    def test_non_string_blocked_role_prefixes_element_fails_fast(self):
        # An array with a non-string element is not a Vec<String> and the gateway
        # would reject it; fail fast with a clear message.
        self._write_raw_config(
            lambda c: c.__setitem__("BlockedRolePrefixes", ["documentdb", 123])
        )
        result = self._run_entrypoint(
            "--password", "mypassword", extra_env={"USERNAME": "docdb_admin"}
        )
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("must contain only strings", result.stdout + result.stderr)

    def test_empty_blocked_role_prefixes_allows_non_reserved_username(self):
        # An empty array disables prefix blocking, but exact internal role names
        # remain reserved. A non-reserved username that the default prefix policy
        # would block must pass validation.
        self._set_blocked_role_prefixes([])
        result = self._run_entrypoint(
            "--password", "mypassword", extra_env={"USERNAME": "documentdb_service"}
        )
        self.assertEqual(result.returncode, 0, msg=result.stdout + result.stderr)
        self.assertNotIn("reserved prefix", result.stdout + result.stderr)


class InitDataAttemptMarkerTests(unittest.TestCase):
    """Exercises the real init_documentdb_data.sh --attempt-marker contract (#612).

    The marker is written immediately before the first user script runs. If it cannot
    be persisted, initialization must abort before touching any data so a retry stays
    safe (no partially-applied, non-idempotent scripts that could loop on restart).
    """

    INIT_SCRIPT = (
        REPO_ROOT / "documentdb-local" / "scripts" / "init_documentdb_data.sh"
    )

    def setUp(self):
        self.temp_dir = tempfile.TemporaryDirectory()
        self.root = Path(self.temp_dir.name)
        self.bin_dir = self.root / "bin"
        self.init_dir = self.root / "init"
        self.bin_dir.mkdir()
        self.init_dir.mkdir()
        (self.init_dir / "00-data.js").write_text("// data\n", encoding="utf-8")
        # Records each `mongosh --file` execution so a test can assert whether any user
        # script actually ran. The readiness ping (`--eval`) is treated as a no-op.
        self.file_runs = self.root / "mongosh_file_runs"
        # Records whether the attempt marker already existed at the moment the first user
        # script was invoked, so a test can prove the marker is written BEFORE (not after)
        # any data is mutated -- the core ordering invariant of the #612 fix.
        self.marker_state = self.root / "marker_state_at_file_run"
        mongosh = self.bin_dir / "mongosh"
        mongosh.write_text(
            "#!/bin/sh\n"
            'for a in "$@"; do\n'
            '  if [ "$a" = "--file" ]; then\n'
            '    if [ -f "$ATTEMPT_MARKER_PATH" ]; then\n'
            f'      echo present >> "{self.marker_state}"\n'
            "    else\n"
            f'      echo missing >> "{self.marker_state}"\n'
            "    fi\n"
            f'    echo ran >> "{self.file_runs}"\n'
            "    exit 0\n"
            "  fi\n"
            "done\n"
            "exit 0\n",
            encoding="utf-8",
        )
        mongosh.chmod(0o755)

    def tearDown(self):
        self.temp_dir.cleanup()

    def _run(self, attempt_marker, init_dir=None):
        env = os.environ.copy()
        env["PATH"] = f"{self.bin_dir}{os.pathsep}{env['PATH']}"
        env["ENTRYPOINT_LOG"] = str(self.root / "entrypoint.log")
        env["ATTEMPT_MARKER_PATH"] = str(attempt_marker)
        return subprocess.run(
            [
                "bash",
                str(self.INIT_SCRIPT),
                "-H", "localhost",
                "-P", "10260",
                "-u", "u",
                "-p", "p",
                "-d", str(init_dir or self.init_dir),
                "--attempt-marker", str(attempt_marker),
                "-v",
            ],
            env=env,
            text=True,
            capture_output=True,
            timeout=30,
        )

    def test_marker_write_failure_aborts_before_running_scripts(self):
        # A parent path component is a regular file, so `mkdir -p` can never succeed
        # (ENOTDIR) -- this holds even for root, unlike a chmod-based read-only dir.
        blocker = self.root / "not_a_dir"
        blocker.write_text("x", encoding="utf-8")
        bad_marker = blocker / "sub" / "custom_data_attempted"

        result = self._run(bad_marker)
        self.assertNotEqual(result.returncode, 0, msg=result.stdout + result.stderr)
        self.assertFalse(
            self.file_runs.exists(),
            "no user script may run if the attempt marker cannot be written",
        )
        self.assertIn(
            "could not write initialization marker", result.stdout + result.stderr
        )

    def test_marker_written_before_first_script_runs(self):
        marker = self.root / "data" / ".documentdb-local" / "custom_data_attempted"
        result = self._run(marker)
        self.assertEqual(result.returncode, 0, msg=result.stdout + result.stderr)
        self.assertTrue(marker.exists(), "attempt marker should be written")
        self.assertTrue(
            self.file_runs.exists(), "user script should run after the marker is written"
        )
        # The marker must already exist at the moment the first user script is invoked --
        # writing it afterward would re-open the #612 loop on a partial failure.
        self.assertEqual(
            self.marker_state.read_text(encoding="utf-8").strip(),
            "present",
            "attempt marker must be written BEFORE the first user script runs",
        )

    def test_partial_failure_still_records_attempt_marker(self):
        # Real #612 shape: the first script succeeds, a later one fails. The marker must
        # already be present (it is written before the first script), so the entrypoint
        # skips the whole set on restart rather than re-running the non-idempotent first one.
        (self.init_dir / "01-more.js").write_text("// more\n", encoding="utf-8")
        mongosh = self.bin_dir / "mongosh"
        mongosh.write_text(
            "#!/bin/sh\n"
            'for a in "$@"; do\n'
            '  if [ "$a" = "--file" ]; then\n'
            f'    echo ran >> "{self.file_runs}"\n'
            f'    n=$(wc -l < "{self.file_runs}")\n'
            '    if [ "$n" -ge 2 ]; then exit 1; fi\n'
            "    exit 0\n"
            "  fi\n"
            "done\n"
            "exit 0\n",
            encoding="utf-8",
        )
        mongosh.chmod(0o755)

        marker = self.root / "data" / ".documentdb-local" / "custom_data_attempted"
        result = self._run(marker)
        self.assertNotEqual(result.returncode, 0, msg=result.stdout + result.stderr)
        self.assertTrue(
            marker.exists(),
            "attempt marker must persist even when a later script fails",
        )
        self.assertEqual(
            len(self.file_runs.read_text(encoding="utf-8").splitlines()),
            2,
            "both scripts should be attempted before the failure",
        )

    def test_no_js_files_does_not_write_marker(self):
        # No user scripts means no data is mutated, so no marker should be written -- the
        # volume stays eligible for a real initialization later (no spurious one-shot lock).
        empty_dir = self.root / "empty_init"
        empty_dir.mkdir()
        marker = self.root / "data" / ".documentdb-local" / "custom_data_attempted"
        result = self._run(marker, init_dir=empty_dir)
        self.assertNotEqual(result.returncode, 0, msg=result.stdout + result.stderr)
        self.assertFalse(marker.exists(), "no marker may be written when no scripts run")
        self.assertFalse(self.file_runs.exists(), "no user script should run")


class ValidateUsernameScriptTests(unittest.TestCase):
    """Direct tests for documentdb_validate_username.sh, invoked standalone with
    a stubbed jq and a temp SetupConfiguration.json -- covering the reserved-name
    and BlockedRolePrefixes logic without booting the whole entrypoint."""

    VALIDATOR = (
        REPO_ROOT / "documentdb-local" / "scripts" / "documentdb_validate_username.sh"
    )
    RESERVED_ROLES_FILE = (
        REPO_ROOT / "documentdb-local" / "scripts" / "documentdb_reserved_roles.sh"
    )

    def setUp(self):
        self.temp_dir = tempfile.TemporaryDirectory()
        self.root = Path(self.temp_dir.name)
        self.bin_dir = self.root / "bin"
        self.bin_dir.mkdir()
        jq = self.bin_dir / "jq"
        jq.write_text(
            """#!/usr/bin/env python3
import json, sys
rest = [a for a in sys.argv[1:] if not a.startswith('-')]
expr, file_path = rest[0].strip(), rest[1]
with open(file_path, encoding='utf-8') as f:
    data = json.load(f)
if expr == '.BlockedRolePrefixes | type':
    v = data.get('BlockedRolePrefixes')
    print('null' if v is None else 'array' if isinstance(v, list)
          else 'string' if isinstance(v, str) else 'boolean' if isinstance(v, bool)
          else 'number' if isinstance(v, (int, float)) else 'object')
    raise SystemExit(0)
if expr == 'all(.BlockedRolePrefixes[]; type == "string")':
    arr = data.get('BlockedRolePrefixes') or []
    raise SystemExit(0 if isinstance(arr, list) and all(isinstance(x, str) for x in arr) else 1)
if expr in ('.BlockedRolePrefixes[]', '.BlockedRolePrefixes[]?'):
    for item in data.get('BlockedRolePrefixes', []):
        print(item)
    raise SystemExit(0)
raise SystemExit('Unsupported jq expression: ' + expr)
""",
            encoding="utf-8",
        )
        jq.chmod(0o755)
        self.config = self.root / "SetupConfiguration.json"
        self._write_prefixes(["documentdb", "citus", "pg", "internal_role"])

    def tearDown(self):
        self.temp_dir.cleanup()

    def _write_prefixes(self, prefixes):
        self.config.write_text(
            json.dumps({"BlockedRolePrefixes": prefixes}), encoding="utf-8"
        )

    def _run(self, username, config=None, gateway_home=None):
        env = os.environ.copy()
        env["PATH"] = f"{self.bin_dir}:{env['PATH']}"
        args = ["bash", str(self.VALIDATOR), username]
        if config is not None:
            args.append(str(config))
        if gateway_home is not None:
            env["GATEWAY_HOME"] = str(gateway_home)
        return subprocess.run(args, capture_output=True, text=True, env=env)

    def _reserved_role_names(self):
        # Source the file and read the array, so we get exactly its entries and
        # not quoted strings that appear in comments.
        result = subprocess.run(
            [
                "bash",
                "-c",
                f'source "{self.RESERVED_ROLES_FILE}"; '
                'printf "%s\\n" "${DOCUMENTDB_RESERVED_ROLE_NAMES[@]}"',
            ],
            capture_output=True,
            text=True,
        )
        return [line for line in result.stdout.splitlines() if line]

    def test_allowed_username_exits_zero(self):
        result = self._run("docdb_admin", config=self.config)
        self.assertEqual(result.returncode, 0, msg=result.stdout + result.stderr)

    def test_citus_username_is_rejected(self):
        # The exact issue #650 reproduction.
        result = self._run("citus", config=self.config)
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("uses reserved prefix 'citus'", result.stdout + result.stderr)

    def test_every_configured_prefix_is_rejected(self):
        for prefix in ("documentdb", "citus", "pg", "internal_role"):
            with self.subTest(prefix=prefix):
                result = self._run(f"{prefix}_svc", config=self.config)
                self.assertNotEqual(result.returncode, 0)
                self.assertIn(
                    f"uses reserved prefix '{prefix}'", result.stdout + result.stderr
                )

    def test_prefix_check_is_case_insensitive(self):
        result = self._run("DOCUMENTDB_svc", config=self.config)
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("uses reserved prefix 'documentdb'", result.stdout + result.stderr)

    def test_every_reserved_role_name_is_rejected(self):
        # Empty prefixes isolate the exact-name check, which sources the list
        # from documentdb_reserved_roles.sh.
        self._write_prefixes([])
        names = self._reserved_role_names()
        self.assertGreaterEqual(len(names), 11, "reserved-roles data file looks empty")
        for name in names:
            with self.subTest(role=name):
                result = self._run(name, config=self.config)
                self.assertNotEqual(result.returncode, 0)
                self.assertIn(
                    "is reserved for an internal DocumentDB role",
                    result.stdout + result.stderr,
                )

    def test_missing_config_is_rejected(self):
        result = self._run("docdb_admin", config=self.root / "absent.json")
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("not found", result.stdout + result.stderr)

    def test_non_array_prefixes_is_rejected(self):
        self.config.write_text(
            json.dumps({"BlockedRolePrefixes": "documentdb"}), encoding="utf-8"
        )
        result = self._run("docdb_admin", config=self.config)
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("must be a JSON array", result.stdout + result.stderr)

    def test_empty_prefix_entry_is_rejected(self):
        self._write_prefixes([""])
        result = self._run("docdb_admin", config=self.config)
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("contains an empty entry", result.stdout + result.stderr)

    def test_config_path_defaults_to_gateway_home(self):
        # With no config argument, the validator derives it from GATEWAY_HOME.
        gw = self.root / "gw"
        (gw / "pg_documentdb_gw").mkdir(parents=True)
        (gw / "pg_documentdb_gw" / "SetupConfiguration.json").write_text(
            json.dumps({"BlockedRolePrefixes": ["citus"]}), encoding="utf-8"
        )
        result = self._run("citus", gateway_home=gw)
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("uses reserved prefix 'citus'", result.stdout + result.stderr)


class GatewayPackageImageContractTests(unittest.TestCase):
    def test_clean_install_image_copies_entrypoint_script_dependencies(self):
        scripts_dir = REPO_ROOT / "documentdb-local" / "scripts"
        dockerfile = (
            REPO_ROOT
            / "packaging"
            / "gateway"
            / "test"
            / "Dockerfile_deb_gateway_test"
        ).read_text(encoding="utf-8")
        copied_scripts = set(
            re.findall(
                r"^COPY documentdb-local/scripts/(\S+) ",
                dockerfile,
                re.MULTILINE,
            )
        )

        required_scripts = {ENTRYPOINT.name}
        pending_scripts = [ENTRYPOINT.name]
        while pending_scripts:
            script_name = pending_scripts.pop()
            script_path = scripts_dir / script_name
            self.assertTrue(script_path.is_file(), f"missing script: {script_path}")
            script = script_path.read_text(encoding="utf-8")
            for dependency in re.findall(r"\b([a-z][a-z0-9_-]*\.sh)\b", script):
                if (scripts_dir / dependency).is_file() and dependency not in required_scripts:
                    required_scripts.add(dependency)
                    pending_scripts.append(dependency)

        self.assertEqual(set(), required_scripts - copied_scripts)


class GatewayPackageReadinessTests(unittest.TestCase):
    WAITER = (
        REPO_ROOT
        / "packaging"
        / "test_packages"
        / "test-gateway-install-entrypoint.sh"
    )

    def _run_waiter(self, entrypoint, ready_timeout_seconds, shutdown_timeout_seconds):
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            entrypoint_path = root / "entrypoint.sh"
            entrypoint_path.write_text(entrypoint, encoding="utf-8")
            entrypoint_path.chmod(0o755)
            log_path = root / "entrypoint.log"
            command = """
source "$1"
"$2" > "$3" 2>&1 &
entrypoint_pid=$!
wait_for_gateway_ready "$entrypoint_pid" "$3" "$4" "$5"
"""
            return subprocess.run(
                [
                    "bash",
                    "-c",
                    command,
                    "_",
                    str(self.WAITER),
                    str(entrypoint_path),
                    str(log_path),
                    str(ready_timeout_seconds),
                    str(shutdown_timeout_seconds),
                ],
                capture_output=True,
                text=True,
                timeout=10,
            )

    def test_waiter_reports_entrypoint_exit(self):
        result = self._run_waiter("#!/bin/bash\nexit 42\n", 5, 1)

        self.assertNotEqual(result.returncode, 0)
        self.assertIn(
            "Gateway entrypoint exited with status 42 before becoming ready.",
            result.stderr,
        )

    def test_waiter_force_terminates_hung_entrypoint(self):
        started_at = time.monotonic()
        result = self._run_waiter(
            "#!/bin/bash\ntrap '' TERM\nwhile :; do :; done\n",
            0,
            1,
        )

        self.assertNotEqual(result.returncode, 0)
        self.assertLess(time.monotonic() - started_at, 5)
        self.assertIn("Gateway did not become ready within 0 seconds.", result.stderr)


if __name__ == "__main__":
    unittest.main()
