#!/usr/bin/env bash
#
# SPDX-License-Identifier: MIT
#
# Copyright (c) Microsoft Corporation.
#
# Emit documentdb.conf.sample: the committed sample's handwritten prose with the
# managed-block body regenerated by render_documentdb_pg_conf and
# documentdb_required_preload_libraries from documentdb-tools-lib.sh. Both
# package builds call this; a test holds the committed copy equal to the output.
#
# Usage: generate-conf-sample.sh [--output FILE] [--sample FILE] [--tools-lib FILE]
# --tools-lib points at a staged library so a package build renders its own tree.

set -euo pipefail

die() {
    echo "generate-conf-sample.sh: error: $*" >&2
    exit 1
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SAMPLE="${SCRIPT_DIR}/documentdb.conf.sample"
TOOLS_LIB="${SCRIPT_DIR}/../../documentdb-local/scripts/documentdb-tools-lib.sh"
OUTPUT=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --sample)    [[ $# -ge 2 ]] || die "--sample requires a value";    SAMPLE="$2";    shift 2 ;;
        --tools-lib) [[ $# -ge 2 ]] || die "--tools-lib requires a value"; TOOLS_LIB="$2"; shift 2 ;;
        --output)    [[ $# -ge 2 ]] || die "--output requires a value";    OUTPUT="$2";    shift 2 ;;
        *) die "unknown argument: $1" ;;
    esac
done

[[ -r "${SAMPLE}" ]] || die "cannot read the committed sample at ${SAMPLE}"
[[ -r "${TOOLS_LIB}" ]] || die "cannot read documentdb-tools-lib.sh at ${TOOLS_LIB}"

# shellcheck source=/dev/null
. "${TOOLS_LIB}"
MANAGED_BLOCK_START="${DOCUMENTDB_MANAGED_BLOCK_START}"
MANAGED_BLOCK_END="${DOCUMENTDB_MANAGED_BLOCK_END}"

# No --localhost-conn (per-instance socket dir and port) and no --extended-rum
# (decided by a capability probe on the host): a static sample cannot know either.
# Plain assignments so a failure reaches errexit; inline in an argument it would
# be swallowed and the block rendered without preloads.
# shellcheck disable=SC2034  # read by merge_shared_preload_libraries
HAS_EXTENDED_RUM=false
preload="$(merge_shared_preload_libraries "")" \
    || die "cannot determine the required shared_preload_libraries set"
block="$(render_documentdb_pg_conf --preload "${preload}" --toast "${DOCUMENTDB_DEFAULT_TOAST_COMPRESSION}")" \
    || die "render_documentdb_pg_conf failed"

[[ "$(grep -cxF "${MANAGED_BLOCK_START}" "${SAMPLE}")" == 1 ]] \
    || die "expected exactly one start marker line in ${SAMPLE}"
[[ "$(grep -cxF "${MANAGED_BLOCK_END}" "${SAMPLE}")" == 1 ]] \
    || die "expected exactly one end marker line in ${SAMPLE}"

# Splice: keep everything outside the markers verbatim, replace the body between
# them with the rendered block (one blank line on each side). The block travels
# via the environment so no quoting can mangle it.
generated="$(BLOCK="${block}" awk \
    -v start="${MANAGED_BLOCK_START}" -v end="${MANAGED_BLOCK_END}" '
    $0 == start {
        print
        print ""
        printf "%s\n", ENVIRON["BLOCK"]
        print ""
        skipping = 1
        next
    }
    $0 == end { skipping = 0; print; next }
    skipping { next }
    { print }
    END { if (skipping) exit 3 }
' "${SAMPLE}")" || die "the sample's managed block could not be rewritten (end marker before start marker?)"

if [[ -n "${OUTPUT}" ]]; then
    out_dir="$(dirname "${OUTPUT}")"
    [[ -d "${out_dir}" ]] || install -d "${out_dir}"
    printf '%s\n' "${generated}" > "${OUTPUT}"
    chmod 0644 "${OUTPUT}"
else
    printf '%s\n' "${generated}"
fi
