/*-------------------------------------------------------------------------
 * Copyright (c) Microsoft Corporation.  All rights reserved.
 *
 * include/planner/documentdb_plan_cache.h
 *
 * Common declarations for the pg_documentdb plan cache.
 *
 *-------------------------------------------------------------------------
 */

#ifndef BSON_PLAN_CACHE_H
#define BSON_PLAN_CACHE_H

#include <executor/spi.h>

/*
 * ID prefixes for different types of query.
 *
 * The first 32 bits of a query ID are used to identity the operation,
 * and the latter 32 bits to identify different query variants.
 */
#define QUERY_ID_INSERT (1L << 32)
#define QUERY_ID_UPDATE_BY_TID (2L << 32)
#define QUERY_ID_DELETE_BY_TID (3L << 32)

/* TODO: remove once we fully support let and collation with delete */
#define QUERY_DELETE_WITH_FILTER (4L << 32)
#define QUERY_DELETE_WITH_FILTER_SHARDKEY (5L << 32)
#define QUERY_DELETE_WITH_FILTER_ID (6L << 32)
#define QUERY_DELETE_WITH_FILTER_SHARDKEY_ID (7L << 32)

#define QUERY_CALL_UPDATE_ONE (8L << 32)

#define QUERY_DELETE_ONE (9L << 32)
#define QUERY_DELETE_ONE_ID (10L << 32)
#define QUERY_DELETE_ONE_ID_RETURN_DOCUMENT (11L << 32)

/* TODO: remove once we fully support let and collation with delete */
#define QUERY_UPDATE_SELECT_UPDATE_CANDIDATE (12L << 32)
#define QUERY_UPDATE_SELECT_UPDATE_CANDIDATE_NON_OBJECT_ID (13L << 32)
#define QUERY_UPDATE_SELECT_UPDATE_CANDIDATE_ONLY_OBJECT_ID (14L << 32)
#define QUERY_UPDATE_SELECT_UPDATE_CANDIDATE_BOTH_FILTER (15L << 32)


#define QUERY_ID_RETRY_RECORD_INSERT (20L << 32)
#define QUERY_ID_RETRY_RECORD_DELETE (21L << 32)
#define QUERY_ID_RETRY_RECORD_SELECT (22L << 32)

#define QUERY_ID_INSERT_OR_REPLACE (24L << 32)

#define QUERY_ID_GLOBAL_RETRY_RECORD_INSERT (25L << 32)
#define QUERY_ID_GLOBAL_RETRY_RECORD_DELETE (26L << 32)
#define QUERY_ID_GLOBAL_RETRY_RECORD_SELECT (27L << 32)

#define QUERY_DELETE_WITH_FILTER_LET_AND_COLLATION (30L << 32)
#define QUERY_DELETE_WITH_FILTER_SHARDKEY_LET_AND_COLLATION (31L << 32)
#define QUERY_DELETE_WITH_FILTER_ID_LET_AND_COLLATION (32L << 32)
#define QUERY_DELETE_WITH_FILTER_SHARDKEY_ID_LET_AND_COLLATION (33L << 32)

#define QUERY_DELETE_ONE_LET_AND_COLLATION (34L << 32)
#define QUERY_DELETE_ONE_ID_LET_AND_COLLATION (35L << 32)

#define QUERY_UPDATE_SELECT_UPDATE_CANDIDATE_LET_AND_COLLATION (36L << 32)
#define QUERY_UPDATE_SELECT_UPDATE_CANDIDATE_NON_OBJECT_ID_LET_AND_COLLATION (37L << 32)
#define QUERY_UPDATE_SELECT_UPDATE_CANDIDATE_BOTH_FILTER_LET_AND_COLLATION (38L << 32)


#define QUERY_UPDATE_MANY_SHARD_KEY_QUERY_OFFSET (1L << 32)
#define QUERY_UPDATE_MANY_OBJECTID_QUERY_OFFSET (2L << 32)

/* 40L << 32 to 42L << 32 */
#define QUERY_UPDATE_MANY_WITH_QUERY_FILTER_FUNCTION (40L << 32)
#define QUERY_UPDATE_MANY_WITH_QUERY_FILTER_FUNCTION_WITH_SHARD_KEY \
	QUERY_UPDATE_MANY_WITH_QUERY_FILTER_FUNCTION + \
	QUERY_UPDATE_MANY_SHARD_KEY_QUERY_OFFSET
#define QUERY_UPDATE_MANY_WITH_QUERY_FILTER_FUNCTION_WITH_OBJECT_ID \
	QUERY_UPDATE_MANY_WITH_QUERY_FILTER_FUNCTION + QUERY_UPDATE_MANY_OBJECTID_QUERY_OFFSET


/* 43L << 32 to 45L << 32 */
#define QUERY_UPDATE_MANY_WITH_QUERY_FILTER_OPERATOR (43L << 32)
#define QUERY_UPDATE_MANY_WITH_QUERY_FILTER_OPERATOR_WITH_SHARD_KEY \
	QUERY_UPDATE_MANY_WITH_QUERY_FILTER_OPERATOR + \
	QUERY_UPDATE_MANY_SHARD_KEY_QUERY_OFFSET
#define QUERY_UPDATE_MANY_WITH_QUERY_FILTER_OPERATOR_WITH_OBJECT_ID \
	QUERY_UPDATE_MANY_WITH_QUERY_FILTER_OPERATOR + QUERY_UPDATE_MANY_OBJECTID_QUERY_OFFSET

/* Plan IDs for delete_one with _id-only filter (no @@ operator) 46L << 32 to 49L << 32 */
#define QUERY_DELETE_ONE_NO_FILTER (46L << 32)
#define QUERY_DELETE_ONE_ID_ONLY (47L << 32)
#define QUERY_DELETE_ONE_ID_ONLY_RETURN_DOCUMENT (48L << 32)
#define QUERY_DELETE_ONE_NO_FILTER_RETURN_DOCUMENT (49L << 32)

/* Plan IDs for delete_one with returnDeletedDocument 50L << 32 to 52L << 32 */
#define QUERY_DELETE_ONE_RETURN_DOCUMENT (50L << 32)
#define QUERY_DELETE_ONE_LET_AND_COLLATION_RETURN_DOCUMENT (51L << 32)
#define QUERY_DELETE_ONE_ID_LET_AND_COLLATION_RETURN_DOCUMENT (52L << 32)

/* Plan Id for update worker pushdown on sharded collections */
#define QUERY_UPDATE_MANY_PUSHDOWN_QUERY_OFFSET (13L << 32)

/* 53L << 32 to 55L << 32 */
#define QUERY_UPDATE_MANY_WITH_QUERY_FILTER_FUNCTION_PUSHDOWN \
	QUERY_UPDATE_MANY_WITH_QUERY_FILTER_FUNCTION + QUERY_UPDATE_MANY_PUSHDOWN_QUERY_OFFSET
#define QUERY_UPDATE_MANY_WITH_QUERY_FILTER_FUNCTION_WITH_SHARD_KEY_PUSHDOWN \
	QUERY_UPDATE_MANY_WITH_QUERY_FILTER_FUNCTION_WITH_SHARD_KEY + \
	QUERY_UPDATE_MANY_PUSHDOWN_QUERY_OFFSET
#define QUERY_UPDATE_MANY_WITH_QUERY_FILTER_FUNCTION_WITH_OBJECT_ID_PUSHDOWN \
	QUERY_UPDATE_MANY_WITH_QUERY_FILTER_FUNCTION_WITH_OBJECT_ID + \
	QUERY_UPDATE_MANY_PUSHDOWN_QUERY_OFFSET


/* 56L << 32 to 58L << 32 */
#define QUERY_UPDATE_MANY_WITH_QUERY_FILTER_OPERATOR_PUSHDOWN \
	QUERY_UPDATE_MANY_WITH_QUERY_FILTER_OPERATOR + QUERY_UPDATE_MANY_PUSHDOWN_QUERY_OFFSET
#define QUERY_UPDATE_MANY_WITH_QUERY_FILTER_OPERATOR_PUSHDOWN_WITH_SHARD_KEY \
	QUERY_UPDATE_MANY_WITH_QUERY_FILTER_OPERATOR_WITH_SHARD_KEY + \
	QUERY_UPDATE_MANY_PUSHDOWN_QUERY_OFFSET
#define QUERY_UPDATE_MANY_WITH_QUERY_FILTER_OPERATOR_PUSHDOWN_WITH_OBJECT_ID \
	QUERY_UPDATE_MANY_WITH_QUERY_FILTER_OPERATOR_WITH_OBJECT_ID + \
	QUERY_UPDATE_MANY_PUSHDOWN_QUERY_OFFSET

/*
 * Compile-time plan cache ID collision detection.
 *
 * Every plan cache ID must appear exactly once in the array below via the
 * PlanCacheIdEntry macro. Each entry stores its own shifted value at the
 * corresponding index, enabling both compile-time collision detection
 * (-Woverride-init) and runtime Assert validation.
 *
 * WHEN ADDING A NEW PLAN ID:
 *   1. Add the #define above.
 *   2. Add a PlanCacheIdEntry(NEW_ID) line below.
 *   3. Build — collisions fail compilation.
 */

/* Array size is 256 (indices 0-255). Valid plan IDs range from 1 to 255.
 * IDs exceeding 255 cause a compile error (designated initializer out of bounds). */
#define PLAN_CACHE_ARRAY_SIZE 256
#define PlanCacheIdEntry(x) [(x) >> 32] = (uint8) ((x) >> 32)

/* indent tool incorrectly strips the trailing semicolon from designated
 * initializer arrays, causing a compile error. Disable formatting here. */

/* *INDENT-OFF* */
static const uint8 _plan_cache_id_collision_check[PLAN_CACHE_ARRAY_SIZE]
pg_attribute_unused() =
{
	/* Fixed plan IDs (1-15) */
	PlanCacheIdEntry(QUERY_ID_INSERT),
	PlanCacheIdEntry(QUERY_ID_UPDATE_BY_TID),
	PlanCacheIdEntry(QUERY_ID_DELETE_BY_TID),
	PlanCacheIdEntry(QUERY_DELETE_WITH_FILTER),
	PlanCacheIdEntry(QUERY_DELETE_WITH_FILTER_SHARDKEY),
	PlanCacheIdEntry(QUERY_DELETE_WITH_FILTER_ID),
	PlanCacheIdEntry(QUERY_DELETE_WITH_FILTER_SHARDKEY_ID),
	PlanCacheIdEntry(QUERY_CALL_UPDATE_ONE),
	PlanCacheIdEntry(QUERY_DELETE_ONE),
	PlanCacheIdEntry(QUERY_DELETE_ONE_ID),
	PlanCacheIdEntry(QUERY_DELETE_ONE_ID_RETURN_DOCUMENT),
	PlanCacheIdEntry(QUERY_UPDATE_SELECT_UPDATE_CANDIDATE),
	PlanCacheIdEntry(QUERY_UPDATE_SELECT_UPDATE_CANDIDATE_NON_OBJECT_ID),
	PlanCacheIdEntry(QUERY_UPDATE_SELECT_UPDATE_CANDIDATE_ONLY_OBJECT_ID),
	PlanCacheIdEntry(QUERY_UPDATE_SELECT_UPDATE_CANDIDATE_BOTH_FILTER),

	/* Retry/global IDs (20-27) */
	PlanCacheIdEntry(QUERY_ID_RETRY_RECORD_INSERT),
	PlanCacheIdEntry(QUERY_ID_RETRY_RECORD_DELETE),
	PlanCacheIdEntry(QUERY_ID_RETRY_RECORD_SELECT),
	PlanCacheIdEntry(QUERY_ID_INSERT_OR_REPLACE),
	PlanCacheIdEntry(QUERY_ID_GLOBAL_RETRY_RECORD_INSERT),
	PlanCacheIdEntry(QUERY_ID_GLOBAL_RETRY_RECORD_DELETE),
	PlanCacheIdEntry(QUERY_ID_GLOBAL_RETRY_RECORD_SELECT),

	/* Delete with let/collation (30-38) */
	PlanCacheIdEntry(QUERY_DELETE_WITH_FILTER_LET_AND_COLLATION),
	PlanCacheIdEntry(QUERY_DELETE_WITH_FILTER_SHARDKEY_LET_AND_COLLATION),
	PlanCacheIdEntry(QUERY_DELETE_WITH_FILTER_ID_LET_AND_COLLATION),
	PlanCacheIdEntry(QUERY_DELETE_WITH_FILTER_SHARDKEY_ID_LET_AND_COLLATION),
	PlanCacheIdEntry(QUERY_DELETE_ONE_LET_AND_COLLATION),
	PlanCacheIdEntry(QUERY_DELETE_ONE_ID_LET_AND_COLLATION),
	PlanCacheIdEntry(QUERY_UPDATE_SELECT_UPDATE_CANDIDATE_LET_AND_COLLATION),
	PlanCacheIdEntry(QUERY_UPDATE_SELECT_UPDATE_CANDIDATE_NON_OBJECT_ID_LET_AND_COLLATION),
	PlanCacheIdEntry(QUERY_UPDATE_SELECT_UPDATE_CANDIDATE_BOTH_FILTER_LET_AND_COLLATION),

	/* Update-many variants (40-45) */
	PlanCacheIdEntry(QUERY_UPDATE_MANY_WITH_QUERY_FILTER_FUNCTION),
	PlanCacheIdEntry(QUERY_UPDATE_MANY_WITH_QUERY_FILTER_FUNCTION_WITH_SHARD_KEY),
	PlanCacheIdEntry(QUERY_UPDATE_MANY_WITH_QUERY_FILTER_FUNCTION_WITH_OBJECT_ID),
	PlanCacheIdEntry(QUERY_UPDATE_MANY_WITH_QUERY_FILTER_OPERATOR),
	PlanCacheIdEntry(QUERY_UPDATE_MANY_WITH_QUERY_FILTER_OPERATOR_WITH_SHARD_KEY),
	PlanCacheIdEntry(QUERY_UPDATE_MANY_WITH_QUERY_FILTER_OPERATOR_WITH_OBJECT_ID),

	/* Delete-one extended variants (46-52) */
	PlanCacheIdEntry(QUERY_DELETE_ONE_NO_FILTER),
	PlanCacheIdEntry(QUERY_DELETE_ONE_ID_ONLY),
	PlanCacheIdEntry(QUERY_DELETE_ONE_ID_ONLY_RETURN_DOCUMENT),
	PlanCacheIdEntry(QUERY_DELETE_ONE_NO_FILTER_RETURN_DOCUMENT),
	PlanCacheIdEntry(QUERY_DELETE_ONE_RETURN_DOCUMENT),
	PlanCacheIdEntry(QUERY_DELETE_ONE_LET_AND_COLLATION_RETURN_DOCUMENT),
	PlanCacheIdEntry(QUERY_DELETE_ONE_ID_LET_AND_COLLATION_RETURN_DOCUMENT),

	/* Update-many pushdown variants (53-58) */
	PlanCacheIdEntry(QUERY_UPDATE_MANY_WITH_QUERY_FILTER_FUNCTION_PUSHDOWN),
	PlanCacheIdEntry(QUERY_UPDATE_MANY_WITH_QUERY_FILTER_FUNCTION_WITH_SHARD_KEY_PUSHDOWN),
	PlanCacheIdEntry(QUERY_UPDATE_MANY_WITH_QUERY_FILTER_FUNCTION_WITH_OBJECT_ID_PUSHDOWN),
	PlanCacheIdEntry(QUERY_UPDATE_MANY_WITH_QUERY_FILTER_OPERATOR_PUSHDOWN),
	PlanCacheIdEntry(QUERY_UPDATE_MANY_WITH_QUERY_FILTER_OPERATOR_PUSHDOWN_WITH_SHARD_KEY),
	PlanCacheIdEntry(QUERY_UPDATE_MANY_WITH_QUERY_FILTER_OPERATOR_PUSHDOWN_WITH_OBJECT_ID),
};
/* *INDENT-ON* */

/* GUC that controls the query plan cache size */
extern int QueryPlanCacheSizeLimit;


void InitializeQueryPlanCache(void);
SPIPlanPtr GetSPIQueryPlan(uint64 collectionId, uint64 queryId,
						   const char *query, Oid *argTypes, int argCount);

SPIPlanPtr GetSPIQueryPlanWithLocalShard(uint64 collectionId, const char *shardTableName,
										 uint64 queryId,
										 const char *query, Oid *argTypes, int argCount);

#endif
