pr:  
  branches:  
    include:  
      - main  

pool:
  vmImage: 'ubuntu-latest'

stages:  
- stage: TriggerCompatTestPipeline  
  displayName: "Extract Source Branch Name"  
  jobs:  
  - job: ExtractBranchNameJob  
    steps:  
    - script: |  
        echo "Full source branch reference: $(System.PullRequest.SourceBranch)"  
        # Extract the branch name by removing the 'refs/heads/' prefix  
        SOURCE_BRANCH_NAME=$(System.PullRequest.SourceBranch)  
        SOURCE_BRANCH_NAME=${SOURCE_BRANCH_NAME#refs/heads/}  
        echo "Source branch name is: $SOURCE_BRANCH_NAME"  
          
        # Set the branch name as a pipeline variable  
        echo "##vso[task.setvariable variable=SourceBranchName;isOutput=true]$SOURCE_BRANCH_NAME"  
      displayName: "Extract and Output Source Branch Name"  
  
- stage: MonitorCompatPipeline  
  displayName: "Monitor Compat Pipeline"  
  dependsOn: TriggerCompatTestPipeline  
  jobs:  
  - job: MonitorCompatJob  
    steps:  
    - script: |  
        echo "MonitorCompatJob"  
      displayName: "MonitorCompatJob"  