name: Gateway Image - Build and Push to ACR (Native AMD64 and ARM64)

on:
  push:
    branches:
      - main
      - arm64

permissions:
  id-token: write
  contents: read

jobs:
  build-amd64:
    name: Build and Push AMD64
    runs-on: ubuntu-22.04  # Native AMD64 runner
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Login to ACR
      run: az acr login --name documentdboss

    - name: Build and Push AMD64 Image
      run: |
        IMAGE_TAG=$(date +'%Y-%m-%d')-${{ github.run_id }}-amd64
        docker build \
          --build-arg BASE_ARCH=AMD64 \
          -t documentdboss.azurecr.io/documentdb-gateway-preview:$IMAGE_TAG \
          -f .github/containers/Build-Ubuntu/Dockerfile_gateway .
        docker push documentdboss.azurecr.io/documentdb-gateway-preview:$IMAGE_TAG

  build-arm64:
    name: Build and Push ARM64
    runs-on: ubuntu-22.04-arm  # Native ARM64 runner
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Login to ACR
      run: az acr login --name documentdboss

    - name: Build and Push ARM64 Image
      run: |
        IMAGE_TAG=$(date +'%Y-%m-%d')-${{ github.run_id }}-arm64
        docker build \
          --build-arg BASE_ARCH=ARM64 \
          -t documentdboss.azurecr.io/documentdb-gateway-preview:$IMAGE_TAG \
          -f .github/containers/Build-Ubuntu/Dockerfile_gateway .
        docker push documentdboss.azurecr.io/documentdb-gateway-preview:$IMAGE_TAG
