name: Build and Push to ACR

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: 'Login to Azure'
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: 'Build and Push image to ACR'
      run: |
        IMAGE_TAG=$(date +'%Y-%m-%d')-${{ github.run_id }}
        az acr build \
          --registry pgmongoemulator.azurecr.io \
          --image documentdb-gateway-test:$IMAGE_TAG \
          --file .github/containers/Build-Ubuntu/Dockerfile_gateway \
          .
