name: Gateway Image - Build and Push to GHCR (Native AMD64 and ARM64)

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '*.md'

permissions:
  packages: write
  contents: read

jobs:
  build-amd64:
    name: Build and Push AMD64
    runs-on: ubuntu-22.04  # Native AMD64 runner
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to GHCR
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and Push AMD64 Image
      run: |
        IMAGE_TAG=$(date +'%Y-%m-%d')-${{ github.run_id }}-amd64
        docker build \
          --build-arg BASE_ARCH=AMD64 \
          -t ghcr.io/${{ github.repository }}:$IMAGE_TAG \
          -f .github/containers/Build-Ubuntu/Dockerfile_gateway .
        docker push ghcr.io/${{ github.repository }}:$IMAGE_TAG

  build-arm64:
    name: Build and Push ARM64
    runs-on: ubuntu-22.04-arm  # Native ARM64 runner
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to GHCR
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and Push ARM64 Image
      run: |
        IMAGE_TAG=$(date +'%Y-%m-%d')-${{ github.run_id }}-arm64
        docker build \
          --build-arg BASE_ARCH=ARM64 \
          -t ghcr.io/${{ github.repository }}:$IMAGE_TAG \
          -f .github/containers/Build-Ubuntu/Dockerfile_gateway .
        docker push ghcr.io/${{ github.repository }}$IMAGE_TAG

  create-manifest:
    name: Create and Push Manifest
    runs-on: ubuntu-22.04
    needs: 
      - build-amd64
      - build-arm64
    steps:
    - name: Login to GHCR
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Create and Push Manifest
      run: |
        IMAGE_TAG=$(date +'%Y-%m-%d')-${{ github.run_id }}
        MANIFEST_TAG=preview-test
        docker manifest create ghcr.io/${{ github.repository }}:$MANIFEST_TAG \
          --amend ghcr.io/${{ github.repository }}:$IMAGE_TAG-amd64 \
          --amend ghcr.io/${{ github.repository }}:$IMAGE_TAG-arm64
        docker manifest push ghcr.io/${{ github.repository }}:$MANIFEST_TAG


