name: Functional test report

on:
  workflow_run:
    workflows:
      - DocumentDB functional tests
    types:
      - completed

permissions:
  actions: read
  checks: write
  contents: read

jobs:
  functional-test-report:
    if: >-
      ${{
        github.event.workflow_run.event != 'schedule' &&
        github.event.workflow_run.conclusion != 'cancelled'
      }}
    runs-on: ubuntu-22.04

    steps:
      - name: Publish functional test report
        uses: dorny/test-reporter@v3
        with:
          artifact: functional-test-results-pg17
          name: Functional tests
          path: functional-results.xml
          reporter: python-xunit
          fail-on-empty: false
          fail-on-error: false
          use-actions-summary: true
          max-annotations: 50
